
// This file has been generated by the GUI designer. Do not modify.
namespace courses
{
	public partial class EmptyRegistration
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.Button button4;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget courses.EmptyRegistration
			this.Name = "courses.EmptyRegistration";
			this.Title = global::Mono.Unix.Catalog.GetString("EmptyRegistration");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child courses.EmptyRegistration.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.button4 = new global::Gtk.Button();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Close");
			this.fixed2.Add(this.button4);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.button4]));
			w1.X = 290;
			w1.Y = 243;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 316;
			this.label3.HeightRequest = 56;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("You are wrong input login or password!");
			this.fixed2.Add(this.label3);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label3]));
			w2.X = 51;
			w2.Y = 80;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.button4.Clicked += new global::System.EventHandler(this.OnButton4Clicked);
		}
	}
}
